OPS-234: workaround for missing release branch deployments
Smartwyre/azure-jira-update pull request #1
Opened 2021-11-22 17:45 UTC by booyaa

### Overview 

Add a new function to use git to show commits for a given release. Azure DevOps is unable to show all commit histories for a release branch (this problem does not affect the "main" branch deploys).

I've created a test script so @andysbolton and TBC (someone who knows their way around git) can review

### How the script works

In essence we're performing the following: `git log --oneline --decorate --no-merges <last release branch>...<our release branch>`.

Most of the script involves working out what the last release branch is in the context of our release branch e.g. If our release branch is 5.35.0 then our last release branch will be 5..34.2
 
### Assumptions

you've got an up to date copy of `smartwyre-app` and it's in the same directory level as this repo. A

```powershell
cd smartwyre-app
..\azure-jira-update\TestScript.ps1 5.35.0  # view commits relating to 5.35.0
````

2021-11-22 19:54 UTC, lsandoz requested changes
Looks good overall, some small things I noticed. Will approve when fixed.

2021-11-22 19:54 UTC, lsandoz commented on EP.PowerShell.JiraDeployInfo/Public/Update-AzureDeploymentInformation.ps1
> +        $jiraIds += (Get-JiraIDsFrmAzureChanges)
Missing letter calling function, should be Get-JiraIDsFromAzureChanges

2021-11-22 19:54 UTC, lsandoz commented on EP.PowerShell.JiraDeployInfo/Private/Get-JiraIDsFromGitLog.ps1
> +}
Shouldn't this one be the same as the one used on the testing script? Testing this one there didn't succeed to return what we expect. 

I don't know much of ps so maybe this is not that simple but I would try have the TestScript reference the real scripts used on the deploy as to mitigate possible discrepancies between the test version and the real one that could break the pipeline.

2021-11-22 22:26 UTC, andysbolton commented on EP.PowerShell.JiraDeployInfo/Public/Update-AzureDeploymentInformation.ps1
> +    if ($SourceBranch == "main") { # FIXME: hard coded
This will need to be `-eq` instead of `==`.

2021-11-22 22:41 UTC, andysbolton reviewed
The test script looks good and seems to work well. As @lsandoz said, the `EP.PowerShell.JiraDeployInfo/Private/Get-JiraIDsFromGitLog.ps1` function doesn't seem to correctly query for the previous release and returns different results, looks like that just wasn't updated.

2021-11-23 10:14 UTC, booyaa commented on EP.PowerShell.JiraDeployInfo/Public/Update-AzureDeploymentInformation.ps1
> +        $jiraIds += (Get-JiraIDsFrmAzureChanges)
Good catch, not sure why the linter didn't pick it up! 🥇

2021-11-23 11:34 UTC, lsandoz approved these changes
Looks good to me now, nice work

2021-11-24 08:37 UTC, merged